        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE ABORTENERGYPLUS__genmod
          INTERFACE 
            SUBROUTINE ABORTENERGYPLUS
            END SUBROUTINE ABORTENERGYPLUS
          END INTERFACE 
        END MODULE ABORTENERGYPLUS__genmod
