        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE CALCDPNOZ__genmod
          INTERFACE 
            SUBROUTINE CALCDPNOZ(LOAD,REF$,DPNOZ)
              REAL(KIND=4), INTENT(IN) :: LOAD
              CHARACTER(LEN=80), INTENT(IN) :: REF$
              REAL(KIND=4), INTENT(OUT) :: DPNOZ
            END SUBROUTINE CALCDPNOZ
          END INTERFACE 
        END MODULE CALCDPNOZ__genmod
