        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:56 2018
        MODULE CALCFILTERDRIERDP__genmod
          INTERFACE 
            SUBROUTINE CALCFILTERDRIERDP
            END SUBROUTINE CALCFILTERDRIERDP
          END INTERFACE 
        END MODULE CALCFILTERDRIERDP__genmod
