        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:26:02 2018
        MODULE CALCMATRIXMULTVECTOR__genmod
          INTERFACE 
            SUBROUTINE CALCMATRIXMULTVECTOR(M1,NROW,M2,M3)
              INTEGER(KIND=4) :: NROW
              REAL(KIND=4) :: M1(NROW,NROW)
              REAL(KIND=4) :: M2(NROW)
              REAL(KIND=4) :: M3(NROW)
            END SUBROUTINE CALCMATRIXMULTVECTOR
          END INTERFACE 
        END MODULE CALCMATRIXMULTVECTOR__genmod
