        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE CALCQTUBERATED__genmod
          INTERFACE 
            SUBROUTINE CALCQTUBERATED(LTUBE,TITXV,TSOEVP,REF$,QTUBERTD)
              REAL(KIND=4), INTENT(IN) :: LTUBE
              REAL(KIND=4), INTENT(IN) :: TITXV
              REAL(KIND=4), INTENT(IN) :: TSOEVP
              CHARACTER(LEN=80), INTENT(IN) :: REF$
              REAL(KIND=4), INTENT(OUT) :: QTUBERTD
            END SUBROUTINE CALCQTUBERATED
          END INTERFACE 
        END MODULE CALCQTUBERATED__genmod
