        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE CALCQNOZRATED__genmod
          INTERFACE 
            SUBROUTINE CALCQNOZRATED(TITXV,TSOEVP,REF$,QNOZRTD)
              REAL(KIND=4), INTENT(IN) :: TITXV
              REAL(KIND=4), INTENT(IN) :: TSOEVP
              CHARACTER(LEN=80), INTENT(IN) :: REF$
              REAL(KIND=4), INTENT(OUT) :: QNOZRTD
            END SUBROUTINE CALCQNOZRATED
          END INTERFACE 
        END MODULE CALCQNOZRATED__genmod
