        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE CALCDPTUBE__genmod
          INTERFACE 
            SUBROUTINE CALCDPTUBE(LOAD,REF$,DPTUBE)
              REAL(KIND=4), INTENT(IN) :: LOAD
              CHARACTER(LEN=80), INTENT(IN) :: REF$
              REAL(KIND=4), INTENT(OUT) :: DPTUBE
            END SUBROUTINE CALCDPTUBE
          END INTERFACE 
        END MODULE CALCDPTUBE__genmod
