        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:26:02 2018
        MODULE CALCMATRIXMULTMATRIX__genmod
          INTERFACE 
            SUBROUTINE CALCMATRIXMULTMATRIX(M1,NROWM1,NCOLM1,M2,NCOLM2, &
     &M3)
              INTEGER(KIND=4) :: NCOLM2
              INTEGER(KIND=4) :: NCOLM1
              INTEGER(KIND=4) :: NROWM1
              REAL(KIND=4) :: M1(NROWM1,NCOLM1)
              REAL(KIND=4) :: M2(NCOLM1,NCOLM2)
              REAL(KIND=4) :: M3(NROWM1,NCOLM2)
            END SUBROUTINE CALCMATRIXMULTMATRIX
          END INTERFACE 
        END MODULE CALCMATRIXMULTMATRIX__genmod
