        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE CLOSEMISCOPENFILES__genmod
          INTERFACE 
            SUBROUTINE CLOSEMISCOPENFILES
            END SUBROUTINE CLOSEMISCOPENFILES
          END INTERFACE 
        END MODULE CLOSEMISCOPENFILES__genmod
