        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE CONVERTCASETOLOWER__genmod
          INTERFACE 
            SUBROUTINE CONVERTCASETOLOWER(INPUTSTRING,OUTPUTSTRING)
              CHARACTER(*), INTENT(IN) :: INPUTSTRING
              CHARACTER(*), INTENT(OUT) :: OUTPUTSTRING
            END SUBROUTINE CONVERTCASETOLOWER
          END INTERFACE 
        END MODULE CONVERTCASETOLOWER__genmod
