        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE CONVERTCASETOUPPER__genmod
          INTERFACE 
            SUBROUTINE CONVERTCASETOUPPER(INPUTSTRING,OUTPUTSTRING)
              CHARACTER(*), INTENT(IN) :: INPUTSTRING
              CHARACTER(*), INTENT(OUT) :: OUTPUTSTRING
            END SUBROUTINE CONVERTCASETOUPPER
          END INTERFACE 
        END MODULE CONVERTCASETOUPPER__genmod
