        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:05 2018
        MODULE COSTINFOOUT__genmod
          INTERFACE 
            SUBROUTINE COSTINFOOUT
            END SUBROUTINE COSTINFOOUT
          END INTERFACE 
        END MODULE COSTINFOOUT__genmod
