        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:05 2018
        MODULE DETAILSFORSURFACES__genmod
          INTERFACE 
            SUBROUTINE DETAILSFORSURFACES(RPTTYPE)
              INTEGER(KIND=4), INTENT(IN) :: RPTTYPE
            END SUBROUTINE DETAILSFORSURFACES
          END INTERFACE 
        END MODULE DETAILSFORSURFACES__genmod
