        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:57 2018
        MODULE DEWPOINT__genmod
          INTERFACE 
            FUNCTION DEWPOINT(W,BAROPRESSURE)
              REAL(KIND=4) :: W
              REAL(KIND=4) :: BAROPRESSURE
              REAL(KIND=4) :: DEWPOINT
            END FUNCTION DEWPOINT
          END INTERFACE 
        END MODULE DEWPOINT__genmod
