        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:56 2018
        MODULE DISPLAYSTRING__genmod
          INTERFACE 
            SUBROUTINE DISPLAYSTRING(STRING)
              CHARACTER(*), INTENT(IN) :: STRING
            END SUBROUTINE DISPLAYSTRING
          END INTERFACE 
        END MODULE DISPLAYSTRING__genmod
