        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:56 2018
        MODULE DISPLAYNUMBERANDSTRING__genmod
          INTERFACE 
            SUBROUTINE DISPLAYNUMBERANDSTRING(NUMBER,STRING)
              INTEGER(KIND=4), INTENT(IN) :: NUMBER
              CHARACTER(*), INTENT(IN) :: STRING
            END SUBROUTINE DISPLAYNUMBERANDSTRING
          END INTERFACE 
        END MODULE DISPLAYNUMBERANDSTRING__genmod
