        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:56 2018
        MODULE DISPLAYSIMDAYSPROGRESS__genmod
          INTERFACE 
            SUBROUTINE DISPLAYSIMDAYSPROGRESS(CURRENTSIMDAY,TOTALSIMDAYS&
     &)
              INTEGER(KIND=4), INTENT(IN) :: CURRENTSIMDAY
              INTEGER(KIND=4), INTENT(IN) :: TOTALSIMDAYS
            END SUBROUTINE DISPLAYSIMDAYSPROGRESS
          END INTERFACE 
        END MODULE DISPLAYSIMDAYSPROGRESS__genmod
