        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:05 2018
        MODULE DXFOUTLINES__genmod
          INTERFACE 
            SUBROUTINE DXFOUTLINES(COLORSCHEME)
              CHARACTER(*), INTENT(IN) :: COLORSCHEME
            END SUBROUTINE DXFOUTLINES
          END INTERFACE 
        END MODULE DXFOUTLINES__genmod
