        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:05 2018
        MODULE DXFOUT__genmod
          INTERFACE 
            SUBROUTINE DXFOUT(POLYGONACTION,COLORSCHEME)
              CHARACTER(*) :: POLYGONACTION
              CHARACTER(*) :: COLORSCHEME
            END SUBROUTINE DXFOUT
          END INTERFACE 
        END MODULE DXFOUT__genmod
