        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:05 2018
        MODULE DXFOUTWIREFRAME__genmod
          INTERFACE 
            SUBROUTINE DXFOUTWIREFRAME(COLORSCHEME)
              CHARACTER(*), INTENT(IN) :: COLORSCHEME
            END SUBROUTINE DXFOUTWIREFRAME
          END INTERFACE 
        END MODULE DXFOUTWIREFRAME__genmod
