        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE ENDENERGYPLUS__genmod
          INTERFACE 
            SUBROUTINE ENDENERGYPLUS
            END SUBROUTINE ENDENERGYPLUS
          END INTERFACE 
        END MODULE ENDENERGYPLUS__genmod
