        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE FINDNONSPACE__genmod
          INTERFACE 
            FUNCTION FINDNONSPACE(STRING)
              CHARACTER(*), INTENT(IN) :: STRING
              INTEGER(KIND=4) :: FINDNONSPACE
            END FUNCTION FINDNONSPACE
          END INTERFACE 
        END MODULE FINDNONSPACE__genmod
