        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE FINDUNITNUMBER__genmod
          INTERFACE 
            FUNCTION FINDUNITNUMBER(FILENAME) RESULT(UNITNUMBER)
              CHARACTER(*) :: FILENAME
              INTEGER(KIND=4) :: UNITNUMBER
            END FUNCTION FINDUNITNUMBER
          END INTERFACE 
        END MODULE FINDUNITNUMBER__genmod
