        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE GETNEWUNITNUMBER__genmod
          INTERFACE 
            FUNCTION GETNEWUNITNUMBER RESULT(UNITNUMBER)
              INTEGER(KIND=4) :: UNITNUMBER
            END FUNCTION GETNEWUNITNUMBER
          END INTERFACE 
        END MODULE GETNEWUNITNUMBER__genmod
