        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:26:03 2018
        MODULE GUESS3__genmod
          INTERFACE 
            SUBROUTINE GUESS3(LOWERBOUNDVALUEGUESS,                     &
     &FUNCTIONVALFORLOWERBOUNDGUESS,UPPERBOUNDVALUEGUESS,               &
     &FUNCTIONVALFORUPPERBOUNDGUESS,FUNCTIONPOINTERADDRESS,DX,TOL,IERROR&
     &)
              REAL(KIND=4) :: LOWERBOUNDVALUEGUESS
              REAL(KIND=4) :: FUNCTIONVALFORLOWERBOUNDGUESS
              REAL(KIND=4) :: UPPERBOUNDVALUEGUESS
              REAL(KIND=4) :: FUNCTIONVALFORUPPERBOUNDGUESS
              REAL(KIND=4) :: FUNCTIONPOINTERADDRESS
              EXTERNAL FUNCTIONPOINTERADDRESS
              REAL(KIND=4) :: DX
              REAL(KIND=4) :: TOL
              INTEGER(KIND=4) :: IERROR
            END SUBROUTINE GUESS3
          END INTERFACE 
        END MODULE GUESS3__genmod
