        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE ISSUEHPFATALERROR__genmod
          INTERFACE 
            SUBROUTINE ISSUEHPFATALERROR(EXITCODE)
              INTEGER(KIND=4), INTENT(IN) :: EXITCODE
            END SUBROUTINE ISSUEHPFATALERROR
          END INTERFACE 
        END MODULE ISSUEHPFATALERROR__genmod
