        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE ISSUEOUTPUTMESSAGE__genmod
          INTERFACE 
            SUBROUTINE ISSUEOUTPUTMESSAGE(MESSAGE)
              CHARACTER(*), INTENT(IN) :: MESSAGE
            END SUBROUTINE ISSUEOUTPUTMESSAGE
          END INTERFACE 
        END MODULE ISSUEOUTPUTMESSAGE__genmod
