        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:05 2018
        MODULE LINESOUT__genmod
          INTERFACE 
            SUBROUTINE LINESOUT(OPTION)
              CHARACTER(*), INTENT(IN) :: OPTION
            END SUBROUTINE LINESOUT
          END INTERFACE 
        END MODULE LINESOUT__genmod
