        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:26:02 2018
        MODULE MATRIX_INVERT_STEP_2__genmod
          INTERFACE 
            SUBROUTINE MATRIX_INVERT_STEP_2(A,AINV,PIVOT,N)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: A(N,N)
              REAL(KIND=4) :: AINV(N,N)
              INTEGER(KIND=4) :: PIVOT(N)
            END SUBROUTINE MATRIX_INVERT_STEP_2
          END INTERFACE 
        END MODULE MATRIX_INVERT_STEP_2__genmod
