        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:57 2018
        MODULE PSYCHART__genmod
          INTERFACE 
            SUBROUTINE PSYCHART(AIRPROPOPT,AIRPROPERR)
              INTEGER(KIND=2), INTENT(IN) :: AIRPROPOPT
              INTEGER(KIND=2), INTENT(OUT) :: AIRPROPERR
            END SUBROUTINE PSYCHART
          END INTERFACE 
        END MODULE PSYCHART__genmod
