        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:57 2018
        MODULE RELHUM__genmod
          INTERFACE 
            FUNCTION RELHUM(PSAT,HUMRATIO,BAROPRESSURE)
              REAL(KIND=4) :: PSAT
              REAL(KIND=4) :: HUMRATIO
              REAL(KIND=4) :: BAROPRESSURE
              REAL(KIND=4) :: RELHUM
            END FUNCTION RELHUM
          END INTERFACE 
        END MODULE RELHUM__genmod
