        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:04 2018
        MODULE SETUPREALOUTPUTVARIABLE__genmod
          INTERFACE 
            SUBROUTINE SETUPREALOUTPUTVARIABLE(VARIABLENAME,            &
     &ACTUALVARIABLE,INDEXTYPEKEY,VARIABLETYPEKEY,KEYEDVALUE,REPORTFREQ,&
     &RESOURCETYPEKEY,ENDUSEKEY,ENDUSESUBKEY,GROUPKEY,ZONEKEY,ZONEMULT, &
     &ZONELISTMULT,INDEXGROUPKEY)
              CHARACTER(*), INTENT(IN) :: VARIABLENAME
              REAL(KIND=8) ,TARGET, INTENT(IN) :: ACTUALVARIABLE
              CHARACTER(*), INTENT(IN) :: INDEXTYPEKEY
              CHARACTER(*), INTENT(IN) :: VARIABLETYPEKEY
              CHARACTER(*), INTENT(IN) :: KEYEDVALUE
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: REPORTFREQ
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: RESOURCETYPEKEY
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: ENDUSEKEY
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: ENDUSESUBKEY
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: GROUPKEY
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: ZONEKEY
              INTEGER(KIND=4) ,OPTIONAL, INTENT(IN) :: ZONEMULT
              INTEGER(KIND=4) ,OPTIONAL, INTENT(IN) :: ZONELISTMULT
              INTEGER(KIND=4) ,OPTIONAL, INTENT(IN) :: INDEXGROUPKEY
            END SUBROUTINE SETUPREALOUTPUTVARIABLE
          END INTERFACE 
        END MODULE SETUPREALOUTPUTVARIABLE__genmod
