        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWSEVEREERROR1__genmod
          INTERFACE 
            SUBROUTINE SHOWSEVEREERROR1(ERRORMESSAGE,OUTUNIT1)
              CHARACTER(*) :: ERRORMESSAGE
              INTEGER(KIND=4) :: OUTUNIT1
            END SUBROUTINE SHOWSEVEREERROR1
          END INTERFACE 
        END MODULE SHOWSEVEREERROR1__genmod
