        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWSEVEREMESSAGE__genmod
          INTERFACE 
            SUBROUTINE SHOWSEVEREMESSAGE(ERRORMESSAGE,OUTUNIT1,OUTUNIT2)
              CHARACTER(*) :: ERRORMESSAGE
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT1
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT2
            END SUBROUTINE SHOWSEVEREMESSAGE
          END INTERFACE 
        END MODULE SHOWSEVEREMESSAGE__genmod
