        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWWARNINGERROR__genmod
          INTERFACE 
            SUBROUTINE SHOWWARNINGERROR(ERRORMESSAGE,OUTUNIT1,OUTUNIT2)
              CHARACTER(*) :: ERRORMESSAGE
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT1
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT2
            END SUBROUTINE SHOWWARNINGERROR
          END INTERFACE 
        END MODULE SHOWWARNINGERROR__genmod
