        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWSEVEREERROR2__genmod
          INTERFACE 
            SUBROUTINE SHOWSEVEREERROR2(ERRORMESSAGE,OUTUNIT1,OUTUNIT2)
              CHARACTER(*) :: ERRORMESSAGE
              INTEGER(KIND=4) :: OUTUNIT1
              INTEGER(KIND=4) :: OUTUNIT2
            END SUBROUTINE SHOWSEVEREERROR2
          END INTERFACE 
        END MODULE SHOWSEVEREERROR2__genmod
