        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWRECURRINGSEVEREERRORATEND__genmod
          INTERFACE 
            SUBROUTINE SHOWRECURRINGSEVEREERRORATEND(MESSAGE,MSGINDEX,  &
     &REPORTMAXOF,REPORTMINOF,REPORTSUMOF,REPORTMAXUNITS,REPORTMINUNITS,&
     &REPORTSUMUNITS)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4), INTENT(INOUT) :: MSGINDEX
              REAL(KIND=8) ,OPTIONAL, INTENT(IN) :: REPORTMAXOF
              REAL(KIND=8) ,OPTIONAL, INTENT(IN) :: REPORTMINOF
              REAL(KIND=8) ,OPTIONAL, INTENT(IN) :: REPORTSUMOF
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: REPORTMAXUNITS
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: REPORTMINUNITS
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: REPORTSUMUNITS
            END SUBROUTINE SHOWRECURRINGSEVEREERRORATEND
          END INTERFACE 
        END MODULE SHOWRECURRINGSEVEREERRORATEND__genmod
