        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWCONTINUEERRORTIMESTAMP__genmod
          INTERFACE 
            SUBROUTINE SHOWCONTINUEERRORTIMESTAMP(MESSAGE,OUTUNIT1,     &
     &OUTUNIT2)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT1
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT2
            END SUBROUTINE SHOWCONTINUEERRORTIMESTAMP
          END INTERFACE 
        END MODULE SHOWCONTINUEERRORTIMESTAMP__genmod
