        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWFATALERROR__genmod
          INTERFACE 
            SUBROUTINE SHOWFATALERROR(ERRORMESSAGE,OUTUNIT1,OUTUNIT2)
              CHARACTER(*) :: ERRORMESSAGE
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT1
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT2
            END SUBROUTINE SHOWFATALERROR
          END INTERFACE 
        END MODULE SHOWFATALERROR__genmod
