        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE SHOWWARNINGMESSAGE__genmod
          INTERFACE 
            SUBROUTINE SHOWWARNINGMESSAGE(ERRORMESSAGE,OUTUNIT1,OUTUNIT2&
     &)
              CHARACTER(*) :: ERRORMESSAGE
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT1
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT2
            END SUBROUTINE SHOWWARNINGMESSAGE
          END INTERFACE 
        END MODULE SHOWWARNINGMESSAGE__genmod
