        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:04 2018
        MODULE STORERECURRINGERRORMESSAGE__genmod
          INTERFACE 
            SUBROUTINE STORERECURRINGERRORMESSAGE(ERRORMESSAGE,         &
     &ERRORMSGINDEX,ERRORREPORTMAXOF,ERRORREPORTMINOF,ERRORREPORTSUMOF, &
     &ERRORREPORTMAXUNITS,ERRORREPORTMINUNITS,ERRORREPORTSUMUNITS)
              CHARACTER(*) :: ERRORMESSAGE
              INTEGER(KIND=4), INTENT(INOUT) :: ERRORMSGINDEX
              REAL(KIND=8) ,OPTIONAL, INTENT(IN) :: ERRORREPORTMAXOF
              REAL(KIND=8) ,OPTIONAL, INTENT(IN) :: ERRORREPORTMINOF
              REAL(KIND=8) ,OPTIONAL, INTENT(IN) :: ERRORREPORTSUMOF
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: ERRORREPORTMAXUNITS
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: ERRORREPORTMINUNITS
              CHARACTER(*) ,OPTIONAL, INTENT(IN) :: ERRORREPORTSUMUNITS
            END SUBROUTINE STORERECURRINGERRORMESSAGE
          END INTERFACE 
        END MODULE STORERECURRINGERRORMESSAGE__genmod
