        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:27:57 2018
        MODULE TAIRSAT__genmod
          INTERFACE 
            FUNCTION TAIRSAT(HSAT,BAROPRESSURE)
              REAL(KIND=4) :: HSAT
              REAL(KIND=4) :: BAROPRESSURE
              REAL(KIND=4) :: TAIRSAT
            END FUNCTION TAIRSAT
          END INTERFACE 
        END MODULE TAIRSAT__genmod
