        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 30 11:31:05 2018
        MODULE VRMLOUT__genmod
          INTERFACE 
            SUBROUTINE VRMLOUT(POLYGONACTION,COLORSCHEME)
              CHARACTER(*) :: POLYGONACTION
              CHARACTER(*) :: COLORSCHEME
            END SUBROUTINE VRMLOUT
          END INTERFACE 
        END MODULE VRMLOUT__genmod
