        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE ABORTENERGYPLUS__genmod
          INTERFACE 
            SUBROUTINE ABORTENERGYPLUS
            END SUBROUTINE ABORTENERGYPLUS
          END INTERFACE 
        END MODULE ABORTENERGYPLUS__genmod
