        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE CLOSEMISCOPENFILES__genmod
          INTERFACE 
            SUBROUTINE CLOSEMISCOPENFILES
            END SUBROUTINE CLOSEMISCOPENFILES
          END INTERFACE 
        END MODULE CLOSEMISCOPENFILES__genmod
