        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE ENDENERGYPLUS__genmod
          INTERFACE 
            SUBROUTINE ENDENERGYPLUS
            END SUBROUTINE ENDENERGYPLUS
          END INTERFACE 
        END MODULE ENDENERGYPLUS__genmod
