        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE GETNEWUNITNUMBER__genmod
          INTERFACE 
            FUNCTION GETNEWUNITNUMBER RESULT(UNITNUMBER)
              INTEGER(KIND=4) :: UNITNUMBER
            END FUNCTION GETNEWUNITNUMBER
          END INTERFACE 
        END MODULE GETNEWUNITNUMBER__genmod
