        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE ISSUEOUTPUTMESSAGE__genmod
          INTERFACE 
            SUBROUTINE ISSUEOUTPUTMESSAGE(MESSAGE)
              CHARACTER(*), INTENT(IN) :: MESSAGE
            END SUBROUTINE ISSUEOUTPUTMESSAGE
          END INTERFACE 
        END MODULE ISSUEOUTPUTMESSAGE__genmod
