        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE ISSUEHPFATALERROR__genmod
          INTERFACE 
            SUBROUTINE ISSUEHPFATALERROR(EXITCODE)
              INTEGER(KIND=4), INTENT(IN) :: EXITCODE
            END SUBROUTINE ISSUEHPFATALERROR
          END INTERFACE 
        END MODULE ISSUEHPFATALERROR__genmod
