        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE SHOWMESSAGE__genmod
          INTERFACE 
            SUBROUTINE SHOWMESSAGE(MESSAGE,OUTUNIT1,OUTUNIT2)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT1
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT2
            END SUBROUTINE SHOWMESSAGE
          END INTERFACE 
        END MODULE SHOWMESSAGE__genmod
