        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 11 10:55:06 2014
        MODULE SHOWCONTINUEERROR__genmod
          INTERFACE 
            SUBROUTINE SHOWCONTINUEERROR(MESSAGE,OUTUNIT1,OUTUNIT2)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT1
              INTEGER(KIND=4) ,OPTIONAL :: OUTUNIT2
            END SUBROUTINE SHOWCONTINUEERROR
          END INTERFACE 
        END MODULE SHOWCONTINUEERROR__genmod
